# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
  paths:
    include:
    - services/
    - sdk/

pr:
  branches:
    include:
      - main
  paths:
    include:
    - services/
    - sdk/

stages:
- template: /eng/pipelines/templates/stages/run-build-analyze.yml