jobs:
  - job:
    pool:
      vmImage: 'Ubuntu 18.04'

    steps:
      - task: GoTool@0
        inputs:
          version: '1.13'
        displayName: "Select Go Version"
      - template: steps/init_workspace.yml
      - template: steps/linter_check.yml
      - template: steps/build_test.yml
