jobs:
  - job:
    pool:
      vmImage: 'Ubuntu 18.04'
    variables:
      clientID: 9f4340af-57fe-4af3-8a25-91d24bc11f0d
    steps:
      - template: steps/init_workspace.yml
      - template: steps/linter_check.yml
      - template: steps/build_test.yml
      - template: steps/live_test.yml
